"""CLI integration tests.

prepare: no Blender needed — fully verified.
animate/raytrace: require Blender on PATH — skipped if absent.
"""
import shutil
import subprocess
import sys
import csv
import json
from pathlib import Path
import pytest


def _jubilee_root() -> Path:
    from jubilee_twin.paths import resolve
    try:
        return resolve("jubilee_dir")
    except RuntimeError:
        pytest.skip("jubilee.paths/jubilee_dir not registered — run inside virtual environment with science-jubilee installed")


def _latest_gcode() -> str:
    root = _jubilee_root()
    gcode = root / "gcode_logs" / "latest.gcode"
    if not gcode.exists():
        pytest.skip(f"latest.gcode not found at {gcode}")
    return str(gcode)


def _blender_available() -> bool:
    return shutil.which("blender") is not None


# ---------------------------------------------------------------------------
# prepare
# ---------------------------------------------------------------------------

def test_prepare_creates_pipeline_data(tmp_path):
    """prepare writes machine.json and pathout.csv to the given output dir."""
    from jubilee_twin.pipeline import tool_id, path_follower
    from jubilee_twin.paths import resolve

    gcode = _latest_gcode()
    out = str(tmp_path)

    # machine_state.json must exist — skip if not yet generated by an experiment
    try:
        state_path = str(resolve("jubilee_dir") / "gcode_logs" / "machine_state.json")
    except RuntimeError:
        pytest.skip("jubilee_dir entry point not registered")
    import os
    if not os.path.isfile(state_path):
        pytest.skip("gcode_logs/machine_state.json not found — run an experiment first")

    tool_id.run(output_dir=out, machine_state_path=state_path)
    path_follower.run(gcode_file=gcode, output_dir=out)

    machine_json = tmp_path / "machine.json"
    path_csv = tmp_path / "pathout.csv"

    assert machine_json.exists(), "machine.json not created"
    assert path_csv.exists(), "pathout.csv not created"

    machine = json.loads(machine_json.read_text())
    assert len(machine["tools"]) == 4, f"Expected 4 tool slots, got {len(machine['tools'])}"
    assert set(machine["tools"][0]) >= {
        "id", "name", "park", "offsets", "blend", "park_post"
    }

    path_rows = path_csv.read_text().strip().splitlines()
    assert len(path_rows) > 0, "pathout.csv is empty"
    assert len(path_rows[0].split(",")) == 6, "pathout.csv rows must have 6 columns"


def test_prepare_cli_exits_zero():
    """jubilee-twin prepare exits 0 and produces pipeline_data/ CSVs."""
    gcode = _latest_gcode()
    result = subprocess.run(
        [sys.executable, "-m", "jubilee_twin.cli", "prepare", gcode],
        capture_output=True, text=True
    )
    # cli.py has main() not a __main__ block — use the installed script instead
    result = subprocess.run(
        ["jubilee-twin", "prepare", gcode],
        capture_output=True, text=True
    )
    assert result.returncode == 0, f"prepare failed:\n{result.stderr}"
    assert "pipeline_data/ ready" in result.stdout


# ---------------------------------------------------------------------------
# animate  (requires Blender)
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not _blender_available(), reason="blender not on PATH")
def test_animate_cli_exits_zero():
    gcode = _latest_gcode()
    result = subprocess.run(
        ["jubilee-twin", "animate", gcode],
        capture_output=True, encoding="utf-8", errors="replace"
    )
    assert result.returncode == 0, f"animate failed:\n{result.stderr}\n{result.stdout}"


@pytest.mark.skipif(not _blender_available(), reason="blender not on PATH")
def test_animate_produces_csvs():
    """animate regenerates pipeline_data/ CSVs as a side effect."""
    from jubilee_twin.paths import twin_dir
    gcode = _latest_gcode()
    subprocess.run(["jubilee-twin", "animate", gcode], capture_output=True)
    pipeline_data = twin_dir() / "pipeline_data"
    assert (pipeline_data / "machine.json").exists()
    assert (pipeline_data / "pathout.csv").exists()


# ---------------------------------------------------------------------------
# raytrace  (requires Blender)
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not _blender_available(), reason="blender not on PATH")
def test_raytrace_cli_exits_zero():
    """raytrace uses existing pipeline_data/ CSVs (prepare must have run first)."""
    from jubilee_twin.paths import twin_dir
    pipeline_data = twin_dir() / "pipeline_data"
    if not (pipeline_data / "pathout.csv").exists():
        pytest.skip("pipeline_data/pathout.csv missing — run prepare first")

    result = subprocess.run(
        ["jubilee-twin", "raytrace"],
        capture_output=True, encoding="utf-8", errors="replace"
    )
    assert result.returncode == 0, f"raytrace failed:\n{result.stderr}\n{result.stdout}"


def test_raytrace_missing_pipeline_data_raises(tmp_path, monkeypatch):
    """raytrace without pipeline data and without a gcode arg exits with a clear message."""
    import jubilee_twin.paths as paths
    import jubilee_twin.cli as cli

    # Point the CLI at an empty twin dir so the real pipeline_data/ is untouched.
    monkeypatch.setattr(paths, "twin_dir", lambda: tmp_path)
    monkeypatch.setattr("sys.argv", ["jubilee-twin", "raytrace"])

    with pytest.raises(SystemExit) as exit_info:
        cli.main()

    assert "pipeline_data" in str(exit_info.value)
